# Generated by Django 5.0.1 on 2025-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_paymentwebhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentwebhook",
            name="payment_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
