# Generated by Django 5.0.1 on 2025-10-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_paymentwebhook_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="max_devices",
            field=models.IntegerField(default=1),
        ),
    ]
