# Generated by Django 5.0.1 on 2025-10-28 14:33

from django.db import migrations


def fix_max_devices(apps, schema_editor):
    """Set all users' max_devices to 1"""
    User = apps.get_model('billing', 'User')
    User.objects.all().update(max_devices=1)


def reverse_fix_max_devices(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_fix_max_devices"),
    ]

    operations = [
        migrations.RunPython(fix_max_devices, reverse_fix_max_devices),
    ]
