# Generated by Django 4.2 on 2025-12-09 09:43

from django.db import migrations


def normalize_existing_phone_numbers(apps, schema_editor):
    """
    Normalize all existing phone numbers to Tanzania standard format
    """
    User = apps.get_model("billing", "User")
    Payment = apps.get_model("billing", "Payment")
    
    # Function to normalize phone numbers (duplicated here for migration)
    def normalize_phone_number(phone_number):
        if not phone_number:
            return phone_number
        
        # Remove all non-numeric characters except +
        phone = ''.join(c for c in str(phone_number) if c.isdigit() or c == '+')
        phone = phone.replace('+', '')
        
        # Normalize Tanzania phone numbers
        if phone.startswith('255'):
            if len(phone) == 12:
                return phone
        elif phone.startswith('0'):
            if len(phone) == 10:
                return '255' + phone[1:]
        elif len(phone) == 9 and phone.startswith('7'):
            return '255' + phone
        
        # Return original if we can't normalize it
        return phone_number
    
    # Track which numbers we've seen to handle duplicates
    normalized_phones = {}
    users_to_delete = []
    
    # First pass: normalize all user phone numbers and identify duplicates
    for user in User.objects.all().order_by('created_at'):
        original_phone = user.phone_number
        normalized = normalize_phone_number(original_phone)
        
        if normalized != original_phone:
            print(f"Normalizing user {user.id}: {original_phone} -> {normalized}")
        
        if normalized in normalized_phones:
            # Duplicate found - merge this user into the existing one
            existing_user = normalized_phones[normalized]
            
            print(f"Merging duplicate user {user.id} ({original_phone}) into user {existing_user.id} ({existing_user.phone_number})")
            
            # Move payments to the existing user
            Payment.objects.filter(user=user).update(user=existing_user)
            
            # Update existing user's fields with latest information
            if user.paid_until and (not existing_user.paid_until or user.paid_until > existing_user.paid_until):
                existing_user.paid_until = user.paid_until
            
            existing_user.is_active = existing_user.is_active or user.is_active
            existing_user.total_payments += user.total_payments
            existing_user.max_devices = max(existing_user.max_devices or 1, user.max_devices or 1)
            existing_user.save()
            
            # Mark this user for deletion
            users_to_delete.append(user.id)
            
        else:
            # Update phone number and track it
            user.phone_number = normalized
            user.save()
            normalized_phones[normalized] = user
    
    # Delete duplicate users
    if users_to_delete:
        print(f"Deleting {len(users_to_delete)} duplicate users: {users_to_delete}")
        User.objects.filter(id__in=users_to_delete).delete()
    
    # Update payment phone numbers to match normalized format
    for payment in Payment.objects.all():
        original_phone = payment.phone_number
        normalized = normalize_phone_number(original_phone)
        if normalized != original_phone:
            payment.phone_number = normalized
            payment.save()
            print(f"Normalized payment {payment.id} phone: {original_phone} -> {normalized}")


def reverse_normalize_phone_numbers(apps, schema_editor):
    """
    Reverse migration - not implemented as it would be destructive
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_fix_max_devices_to_one"),
    ]

    operations = [
        migrations.RunPython(
            normalize_existing_phone_numbers,
            reverse_normalize_phone_numbers,
        ),
    ]
