# Generated by Django 4.2 on 2026-01-06 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0006_normalize_phone_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("manager_name", models.CharField(blank=True, max_length=100)),
                ("manager_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("yearly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("max_routers", models.IntegerField(default=1)),
                ("max_wifi_users", models.IntegerField(default=100)),
                ("max_vouchers_per_month", models.IntegerField(default=500)),
                ("max_locations", models.IntegerField(default=1)),
                ("max_staff_accounts", models.IntegerField(default=2)),
                ("custom_branding", models.BooleanField(default=False)),
                ("custom_domain", models.BooleanField(default=False)),
                ("api_access", models.BooleanField(default=False)),
                ("white_label", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("analytics_dashboard", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=True)),
                (
                    "revenue_share_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("business_name", models.CharField(max_length=200)),
                ("business_email", models.EmailField(max_length=254)),
                ("business_phone", models.CharField(max_length=20)),
                ("business_address", models.TextField(blank=True)),
                ("country", models.CharField(default="TZ", max_length=2)),
                (
                    "timezone",
                    models.CharField(default="Africa/Dar_es_Salaam", max_length=50),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                ("billing_cycle", models.CharField(default="monthly", max_length=10)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                ("primary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("secondary_color", models.CharField(default="#1E40AF", max_length=7)),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("clickpesa_client_id", models.CharField(blank=True, max_length=255)),
                ("clickpesa_api_key", models.CharField(blank=True, max_length=255)),
                ("nextsms_username", models.CharField(blank=True, max_length=255)),
                ("nextsms_password", models.CharField(blank=True, max_length=255)),
                ("nextsms_sender_id", models.CharField(blank=True, max_length=20)),
                ("api_key", models.CharField(blank=True, max_length=64, unique=True)),
                ("api_secret", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bundle",
            name="currency",
            field=models.CharField(default="TZS", max_length=3),
        ),
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="total_amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="voucher",
            name="bundle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="billing.bundle",
            ),
        ),
        migrations.AlterField(
            model_name="bundle",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="sms_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment Confirmation"),
                    ("expiry_warning", "Expiry Warning"),
                    ("expired", "Access Expired"),
                    ("voucher", "Voucher Redemption"),
                    ("welcome", "Welcome Message"),
                    ("admin", "Admin Notification"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="code",
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="duration_hours",
            field=models.IntegerField(
                choices=[
                    (1, "1 Hour"),
                    (3, "3 Hours"),
                    (6, "6 Hours"),
                    (12, "12 Hours"),
                    (24, "24 Hours (1 Day)"),
                    (72, "72 Hours (3 Days)"),
                    (168, "168 Hours (7 Days)"),
                    (720, "720 Hours (30 Days)"),
                ],
                default=24,
            ),
        ),
        migrations.CreateModel(
            name="TenantSubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("billing_cycle", models.CharField(max_length=10)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_payments",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField(default=8728)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
                ("use_ssl", models.BooleanField(default=False)),
                ("router_model", models.CharField(blank=True, max_length=100)),
                ("router_version", models.CharField(blank=True, max_length=50)),
                ("router_identity", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("configuring", "Configuring"),
                            ("error", "Error"),
                        ],
                        default="configuring",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "hotspot_interface",
                    models.CharField(default="bridge", max_length=50),
                ),
                ("hotspot_profile", models.CharField(default="default", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routers",
                        to="billing.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routers",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.AddField(
            model_name="location",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="billing.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_logs",
                to="billing.router",
            ),
        ),
        migrations.AddField(
            model_name="accesslog",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="bundle",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundles",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="billing.router",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="billing.router",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wifi_payments",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymentwebhook",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_webhooks",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="smslog",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_logs",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wifi_users",
                to="billing.router",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wifi_users",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vouchers",
                to="billing.tenant",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="used_on_router",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redeemed_vouchers",
                to="billing.router",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("tenant", "mac_address")},
        ),
        migrations.CreateModel(
            name="TenantStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("manager", "Manager"),
                            ("support", "Support Staff"),
                            ("viewer", "View Only"),
                        ],
                        default="admin",
                        max_length=20,
                    ),
                ),
                ("can_manage_routers", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=True)),
                ("can_manage_payments", models.BooleanField(default=True)),
                ("can_manage_vouchers", models.BooleanField(default=True)),
                ("can_view_reports", models.BooleanField(default=True)),
                ("can_manage_staff", models.BooleanField(default=False)),
                ("can_manage_settings", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="billing.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role", "user__email"],
                "unique_together": {("tenant", "user")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("tenant", "name")},
        ),
    ]
