# Generated by Django 4.2 on 2026-01-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_location_subscriptionplan_tenant_bundle_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(default="TZS", max_length=3),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="yearly_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="tenantsubscriptionpayment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="tenantsubscriptionpayment",
            name="currency",
            field=models.CharField(default="TZS", max_length=3),
        ),
    ]
