# Generated by Django 4.2 on 2026-01-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_alter_subscriptionplan_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration Verification"),
                            ("password_reset", "Password Reset"),
                            ("email_change", "Email Change"),
                            ("login", "Two-Factor Login"),
                        ],
                        default="registration",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "otp_code", "is_used"],
                name="billing_ema_email_9abff3_idx",
            ),
        ),
    ]
