# Generated by Django 4.2 on 2026-01-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_add_email_otp_and_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("mpesa", "M-Pesa"),
                            ("tigopesa", "TigoPesa"),
                            ("airtel_money", "Airtel Money"),
                            ("halopesa", "HaloPesa"),
                        ],
                        default="mobile_money",
                        max_length=50,
                    ),
                ),
                ("account_number", models.CharField(max_length=100)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("requested_by", models.CharField(blank=True, max_length=200)),
                ("processed_by", models.CharField(blank=True, max_length=200)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tenantpayout",
            index=models.Index(
                fields=["tenant", "status"], name="billing_ten_tenant__edd14a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantpayout",
            index=models.Index(
                fields=["reference"], name="billing_ten_referen_87fa46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantpayout",
            index=models.Index(
                fields=["-requested_at"], name="billing_ten_request_e4bce6_idx"
            ),
        ),
    ]
