# Generated by Django 4.2 on 2026-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_add_tenant_payout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("sales", "Sales Inquiry"),
                            ("support", "Technical Support"),
                            ("partnership", "Partnership Opportunity"),
                            ("demo", "Request Demo"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("replied_by", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["status", "-created_at"], name="billing_con_status_8150ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(fields=["email"], name="billing_con_email_352cad_idx"),
        ),
    ]
