# Generated by Django 4.2 on 2026-01-11 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0011_add_contact_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSBroadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title for this campaign", max_length=200
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="SMS message (max 320 chars for 2 SMS)",
                        max_length=320,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all_users", "All WiFi Users"),
                            ("all_tenants", "All Tenants"),
                            ("tenant_users", "Specific Tenant's Users"),
                            ("active_users", "Active Users Only"),
                            ("expired_users", "Expired Users"),
                            ("custom", "Custom Phone Numbers"),
                        ],
                        default="all_users",
                        max_length=20,
                    ),
                ),
                (
                    "custom_recipients",
                    models.JSONField(
                        blank=True,
                        help_text="List of phone numbers for custom targeting",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, help_text="Schedule for later sending", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required when target_type is 'tenant_users'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_broadcasts",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Broadcast",
                "verbose_name_plural": "SMS Broadcasts",
                "ordering": ["-created_at"],
            },
        ),
    ]
