# Generated by Django 4.2 on 2026-01-11 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_tenant_sms_broadcast"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantsmsbroadcast",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Tenant SMS Broadcast",
                "verbose_name_plural": "Tenant SMS Broadcasts",
            },
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="sms_monthly_allowance",
        ),
        migrations.RemoveField(
            model_name="tenantsmsbroadcast",
            name="created_by",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="sms_broadcast",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="nextsms_base_url",
            field=models.CharField(
                blank=True, default="https://messaging-service.co.tz", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="tenantsmsbroadcast",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True, help_text="Schedule for later sending", null=True
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="sms_type",
            field=models.CharField(
                choices=[
                    ("payment", "Payment Confirmation"),
                    ("expiry_warning", "Expiry Warning"),
                    ("expired", "Access Expired"),
                    ("voucher", "Voucher Redemption"),
                    ("welcome", "Welcome Message"),
                    ("admin", "Admin Notification"),
                    ("broadcast", "Broadcast Message"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsmsbroadcast",
            name="custom_recipients",
            field=models.JSONField(
                blank=True,
                help_text="List of phone numbers for custom targeting",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsmsbroadcast",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tenantsmsbroadcast",
            name="message",
            field=models.TextField(
                help_text="SMS message (max 320 chars for 2 SMS)", max_length=320
            ),
        ),
        migrations.AlterField(
            model_name="tenantsmsbroadcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("sending", "Sending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsmsbroadcast",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("all_users", "All My WiFi Users"),
                    ("active_users", "Active Users Only"),
                    ("expired_users", "Expired Users"),
                    ("expiring_soon", "Expiring Within 24 Hours"),
                    ("custom", "Custom Phone Numbers"),
                ],
                default="all_users",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantsmsbroadcast",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_sms_broadcasts",
                to="billing.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsmsbroadcast",
            name="title",
            field=models.CharField(
                help_text="Internal title for this campaign", max_length=200
            ),
        ),
    ]
