# Generated by Django 4.2 on 2026-01-11 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_add_tenant_sms_broadcast"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoSMSCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("new_user", "New User Registration"),
                            ("payment_success", "Successful Payment"),
                            ("payment_failed", "Failed Payment"),
                            ("access_expiring", "Access Expiring Soon"),
                            ("access_expired", "Access Expired"),
                            ("voucher_redeemed", "Voucher Redeemed"),
                            ("scheduled", "Scheduled (One-time)"),
                            ("recurring_daily", "Daily Recurring"),
                            ("recurring_weekly", "Weekly Recurring"),
                            ("recurring_monthly", "Monthly Recurring"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "hours_before_expiry",
                    models.IntegerField(
                        default=24,
                        help_text="For 'access_expiring' trigger: hours before expiry to send SMS",
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time of day to send (for scheduled/recurring)",
                        null=True,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True,
                        help_text="Date to send (for one-time scheduled)",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0=Monday, 6=Sunday (for weekly recurring)",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month 1-28 (for monthly recurring)",
                        null=True,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="SMS template. Variables: {name}, {phone}, {expiry_date}, {amount}, {bundle}",
                        max_length=320,
                    ),
                ),
                ("target_all_users", models.BooleanField(default=True)),
                ("target_active_only", models.BooleanField(default=False)),
                ("target_expired_only", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_sent", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_sms_campaigns",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto SMS Campaign",
                "verbose_name_plural": "Auto SMS Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "url",
                    models.URLField(
                        help_text="HTTPS URL to receive webhook events", max_length=500
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        help_text="Secret key for HMAC signature verification",
                        max_length=64,
                    ),
                ),
                (
                    "auth_header",
                    models.CharField(
                        blank=True,
                        help_text="Optional Authorization header value",
                        max_length=255,
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of event types to subscribe to"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("failing", "Failing (Retrying)"),
                            ("disabled", "Disabled (Too Many Failures)"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Webhook",
                "verbose_name_plural": "Tenant Webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="advanced_analytics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="auto_sms_campaigns",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="data_export",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="webhook_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("event_id", models.UUIDField(default=uuid.uuid4)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Delivered"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="billing.tenantwebhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("expired_users", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("payment_count", models.IntegerField(default=0)),
                (
                    "avg_payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("vouchers_generated", models.IntegerField(default=0)),
                ("vouchers_redeemed", models.IntegerField(default=0)),
                ("total_devices", models.IntegerField(default=0)),
                ("unique_devices_connected", models.IntegerField(default=0)),
                (
                    "bundle_breakdown",
                    models.JSONField(
                        default=dict, help_text="Revenue and sales count per bundle"
                    ),
                ),
                (
                    "payment_channel_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Revenue per payment channel (M-Pesa, TigoPesa, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Snapshot",
                "verbose_name_plural": "Analytics Snapshots",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AutoSMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_event", models.CharField(max_length=50)),
                ("recipient_phone", models.CharField(max_length=15)),
                ("message_sent", models.TextField()),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="billing.autosmscampaign",
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.payment",
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["webhook", "status"], name="billing_web_webhook_343bdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["status", "next_retry_at"], name="billing_web_status_0c3d72_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantanalyticssnapshot",
            unique_together={("tenant", "date")},
        ),
    ]
