# Generated by Django 4.2 on 2026-01-11 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_add_premium_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouterMonitoringSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_load", models.IntegerField(default=0)),
                ("memory_used", models.BigIntegerField(default=0)),
                ("memory_total", models.BigIntegerField(default=0)),
                ("disk_used", models.BigIntegerField(default=0)),
                ("disk_total", models.BigIntegerField(default=0)),
                ("uptime", models.BigIntegerField(default=0)),
                ("active_hotspot_users", models.IntegerField(default=0)),
                ("total_interfaces", models.IntegerField(default=0)),
                ("interfaces_up", models.IntegerField(default=0)),
                ("rx_bytes", models.BigIntegerField(default=0)),
                ("tx_bytes", models.BigIntegerField(default=0)),
                ("is_reachable", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_snapshots",
                        to="billing.router",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouterHotspotCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("welcome_message", models.TextField(blank=True)),
                ("footer_text", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("background_image_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("secondary_color", models.CharField(default="#1E40AF", max_length=7)),
                ("background_color", models.CharField(default="#F3F4F6", max_length=7)),
                ("text_color", models.CharField(default="#1F2937", max_length=7)),
                ("button_color", models.CharField(default="#3B82F6", max_length=7)),
                (
                    "button_text_color",
                    models.CharField(default="#FFFFFF", max_length=7),
                ),
                ("show_logo", models.BooleanField(default=True)),
                ("show_bundles", models.BooleanField(default=True)),
                ("show_social_login", models.BooleanField(default=False)),
                ("show_terms_link", models.BooleanField(default=True)),
                ("show_support_contact", models.BooleanField(default=True)),
                ("terms_url", models.URLField(blank=True)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=20)),
                ("custom_css", models.TextField(blank=True)),
                ("custom_js", models.TextField(blank=True)),
                ("header_html", models.TextField(blank=True)),
                ("footer_html", models.TextField(blank=True)),
                ("use_custom_template", models.BooleanField(default=False)),
                ("custom_login_html", models.TextField(blank=True)),
                ("custom_logout_html", models.TextField(blank=True)),
                ("custom_status_html", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "router",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_customization",
                        to="billing.router",
                    ),
                ),
            ],
            options={
                "verbose_name": "Router Hotspot Customization",
                "verbose_name_plural": "Router Hotspot Customizations",
            },
        ),
        migrations.CreateModel(
            name="RouterBandwidthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour_start", models.DateTimeField()),
                ("rx_bytes", models.BigIntegerField(default=0)),
                ("tx_bytes", models.BigIntegerField(default=0)),
                ("peak_users", models.IntegerField(default=0)),
                ("avg_users", models.FloatField(default=0)),
                ("avg_rx_rate", models.BigIntegerField(default=0)),
                ("avg_tx_rate", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bandwidth_logs",
                        to="billing.router",
                    ),
                ),
            ],
            options={
                "ordering": ["-hour_start"],
            },
        ),
        migrations.AddIndex(
            model_name="routermonitoringsnapshot",
            index=models.Index(
                fields=["router", "-created_at"], name="billing_rou_router__35857d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routerbandwidthlog",
            index=models.Index(
                fields=["router", "-hour_start"], name="billing_rou_router__b7fef9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routerbandwidthlog",
            unique_together={("router", "hour_start")},
        ),
    ]
