# Generated by Django 4.2 on 2026-02-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_add_snippe_payment_gateway"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPPProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Profile name (synced to MikroTik /ppp/profile name)",
                        max_length=100,
                    ),
                ),
                (
                    "rate_limit",
                    models.CharField(
                        blank=True,
                        help_text="MikroTik rate-limit format: upload/download e.g. '5M/10M'",
                        max_length=100,
                    ),
                ),
                (
                    "local_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Gateway IP assigned to router side of the PPP tunnel",
                        null=True,
                    ),
                ),
                (
                    "remote_address",
                    models.CharField(
                        blank=True,
                        help_text="IP pool name or static IP for the customer side",
                        max_length=100,
                    ),
                ),
                (
                    "dns_server",
                    models.CharField(
                        blank=True,
                        help_text="DNS servers, comma-separated e.g. '8.8.8.8,8.8.4.4'",
                        max_length=255,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("pppoe", "PPPoE"),
                            ("l2tp", "L2TP"),
                            ("pptp", "PPTP"),
                            ("any", "Any"),
                        ],
                        default="pppoe",
                        max_length=10,
                    ),
                ),
                (
                    "session_timeout",
                    models.CharField(
                        blank=True,
                        help_text="Session timeout e.g. '00:00:00' (0 = unlimited)",
                        max_length=20,
                    ),
                ),
                (
                    "idle_timeout",
                    models.CharField(
                        blank=True,
                        help_text="Idle timeout e.g. '00:05:00'",
                        max_length=20,
                    ),
                ),
                (
                    "address_pool",
                    models.CharField(
                        blank=True,
                        help_text="MikroTik IP pool name for dynamic assignment",
                        max_length=100,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default monthly price (TSh) for customers on this profile",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "synced_to_router",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this profile has been pushed to the MikroTik router",
                    ),
                ),
                (
                    "mikrotik_id",
                    models.CharField(
                        blank=True,
                        help_text="MikroTik internal ID (.id) of this profile on the router",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "router",
                    models.ForeignKey(
                        help_text="Router where this profile is provisioned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppp_profiles",
                        to="billing.router",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppp_profiles",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "PPP Profile",
                "verbose_name_plural": "PPP Profiles",
                "ordering": ["tenant", "name"],
                "unique_together": {("tenant", "router", "name")},
            },
        ),
        migrations.CreateModel(
            name="PPPCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="PPPoE login username", max_length=100),
                ),
                (
                    "password",
                    models.CharField(help_text="PPPoE login password", max_length=255),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        help_text="PPPoE service name filter (blank = any)",
                        max_length=50,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address / location"
                    ),
                ),
                (
                    "static_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Fixed remote-address (leave blank for dynamic from pool)",
                        null=True,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="MAC binding for caller-id e.g. 'AA:BB:CC:DD:EE:FF'",
                        max_length=17,
                    ),
                ),
                (
                    "caller_id",
                    models.CharField(
                        blank=True,
                        help_text="Caller-ID restriction (MAC or other identifier)",
                        max_length=100,
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Recurring"),
                            ("prepaid", "Prepaid (days)"),
                            ("unlimited", "Unlimited / Manual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override price (TSh). If blank, uses profile default.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "paid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Service expiry date. Null = never expires (unlimited).",
                        null=True,
                    ),
                ),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("disabled", "Disabled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes (also synced to MikroTik comment)",
                    ),
                ),
                (
                    "synced_to_router",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this secret has been pushed to the MikroTik router",
                    ),
                ),
                (
                    "mikrotik_id",
                    models.CharField(
                        blank=True,
                        help_text="MikroTik internal ID (.id) of this secret on the router",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="PPP profile (speed tier) for this customer",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="billing.pppprofile",
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        help_text="Router where this secret is provisioned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppp_customers",
                        to="billing.router",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppp_customers",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "PPP Customer",
                "verbose_name_plural": "PPP Customers",
                "ordering": ["tenant", "username"],
                "unique_together": {("tenant", "router", "username")},
            },
        ),
    ]
