# Generated by Django 4.2 on 2026-02-19 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0018_pppprofile_pppcustomer"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPPPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "phone_number",
                    models.CharField(help_text="Phone used for payment", max_length=20),
                ),
                ("order_reference", models.CharField(max_length=100, unique=True)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference from Snippe",
                        max_length=100,
                    ),
                ),
                ("payment_channel", models.CharField(default="snippe", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "billing_days",
                    models.IntegerField(
                        default=30, help_text="Number of days this payment covers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.pppcustomer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppp_payments",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "PPP Payment",
                "verbose_name_plural": "PPP Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
