# Generated by Django 4.2 on 2026-02-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_ppppayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPPPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Customer-facing plan name, e.g. 'Home 10Mbps Monthly'",
                        max_length=150,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Customer-facing description of the plan"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price (TSh) per billing cycle",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="TZS", max_length=3)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly (3 months)"),
                            ("biannual", "Bi-Annual (6 months)"),
                            ("annual", "Annual (12 months)"),
                            ("custom", "Custom Days"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "billing_days",
                    models.IntegerField(
                        default=30,
                        help_text="Duration in days this plan grants. Auto-set from billing_cycle unless custom.",
                    ),
                ),
                (
                    "data_limit_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Data cap in GB per cycle. Null = unlimited.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "download_speed",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable download speed e.g. '10 Mbps'",
                        max_length=20,
                    ),
                ),
                (
                    "upload_speed",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable upload speed e.g. '5 Mbps'",
                        max_length=20,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of feature strings, e.g. ["Unlimited data", "Static IP", "24/7 support"]',
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower number = shown first"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as popular/recommended to highlight in customer portal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "promo_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Promotional/discounted price (TSh). Null = no promo.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "promo_label",
                    models.CharField(
                        blank=True,
                        help_text="Promo badge text, e.g. 'Save 20%' or 'New Customer Offer'",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="The MikroTik PPP profile (speed tier) this plan uses",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="billing.pppprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppp_plans",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "PPP Plan",
                "verbose_name_plural": "PPP Plans",
                "ordering": ["tenant", "display_order", "price"],
            },
        ),
        migrations.AddField(
            model_name="pppcustomer",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Billing plan this customer is subscribed to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="billing.pppplan",
            ),
        ),
    ]
