# Generated by Django 4.2 on 2026-02-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0020_pppplan_pppcustomer_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="pppcustomer",
            name="control_number",
            field=models.CharField(
                blank=True,
                help_text="ClickPesa BillPay control number for recurring payments",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="ppppayment",
            name="control_number",
            field=models.CharField(
                blank=True,
                help_text="ClickPesa BillPay control number for this payment",
                max_length=50,
            ),
        ),
    ]
