# Generated by Django 4.2 on 2026-02-23 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0021_add_control_number_to_ppp"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_remote_users",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="remote_user_access",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TenantVPNConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interface_name",
                    models.CharField(
                        default="wg-remote",
                        help_text="WireGuard interface name on the router (max 15 chars)",
                        max_length=15,
                    ),
                ),
                (
                    "listen_port",
                    models.IntegerField(
                        default=51820, help_text="UDP port for WireGuard on the router"
                    ),
                ),
                (
                    "server_private_key",
                    models.CharField(
                        help_text="WireGuard server private key (base64)", max_length=64
                    ),
                ),
                (
                    "server_public_key",
                    models.CharField(
                        help_text="WireGuard server public key (base64)", max_length=64
                    ),
                ),
                (
                    "address_pool",
                    models.CharField(
                        default="10.100.0.0/24",
                        help_text="VPN address pool CIDR (e.g. 10.100.0.0/24)",
                        max_length=18,
                    ),
                ),
                (
                    "server_address",
                    models.GenericIPAddressField(
                        default="10.100.0.1", help_text="Server-side VPN IP address"
                    ),
                ),
                (
                    "dns_servers",
                    models.CharField(
                        default="1.1.1.1, 8.8.8.8",
                        help_text="DNS servers pushed to clients",
                        max_length=100,
                    ),
                ),
                (
                    "mtu",
                    models.IntegerField(
                        default=1420, help_text="MTU for WireGuard tunnel"
                    ),
                ),
                (
                    "persistent_keepalive",
                    models.IntegerField(
                        default=25,
                        help_text="Keepalive interval in seconds (0 to disable)",
                    ),
                ),
                (
                    "enable_nat",
                    models.BooleanField(
                        default=True,
                        help_text="Enable NAT/masquerade for VPN traffic to reach LAN",
                    ),
                ),
                (
                    "enable_firewall_rules",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-create firewall rules for VPN traffic",
                    ),
                ),
                (
                    "allowed_ips",
                    models.CharField(
                        default="0.0.0.0/0",
                        help_text="Default allowed IPs for clients (full tunnel or split)",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_configured_on_router",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the WireGuard interface has been pushed to the router",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time config was synced to the router",
                        null=True,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "router",
                    models.ForeignKey(
                        help_text="Router where WireGuard interface is configured",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_configs",
                        to="billing.router",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_config",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant VPN Configuration",
                "verbose_name_plural": "Tenant VPN Configurations",
            },
        ),
        migrations.CreateModel(
            name="RemoteUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this remote user", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional email for config delivery",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Optional phone number", max_length=20
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this user"
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        help_text="Client WireGuard public key (base64)", max_length=64
                    ),
                ),
                (
                    "private_key",
                    models.CharField(
                        blank=True,
                        help_text="Client private key (only stored temporarily for config generation)",
                        max_length=64,
                    ),
                ),
                (
                    "preshared_key",
                    models.CharField(
                        blank=True,
                        help_text="Optional preshared key for extra security",
                        max_length=64,
                    ),
                ),
                (
                    "assigned_ip",
                    models.GenericIPAddressField(
                        help_text="IP address assigned to this peer from the VPN pool"
                    ),
                ),
                (
                    "allowed_ips",
                    models.CharField(
                        blank=True,
                        help_text="Override allowed IPs for this specific peer",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this user's access expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "bandwidth_limit_up",
                    models.IntegerField(
                        default=0,
                        help_text="Upload bandwidth limit in kbps (0 = unlimited)",
                    ),
                ),
                (
                    "bandwidth_limit_down",
                    models.IntegerField(
                        default=0,
                        help_text="Download bandwidth limit in kbps (0 = unlimited)",
                    ),
                ),
                (
                    "config_downloaded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has downloaded their config file",
                    ),
                ),
                (
                    "is_configured_on_router",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this peer has been pushed to the router",
                    ),
                ),
                (
                    "last_handshake",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last WireGuard handshake time from router",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who created this remote user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_remote_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_users",
                        to="billing.tenant",
                    ),
                ),
                (
                    "vpn_config",
                    models.ForeignKey(
                        help_text="The VPN configuration this user belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_users",
                        to="billing.tenantvpnconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote User",
                "verbose_name_plural": "Remote Users",
                "ordering": ["-created_at"],
                "unique_together": {
                    ("vpn_config", "assigned_ip"),
                    ("vpn_config", "public_key"),
                },
            },
        ),
        migrations.CreateModel(
            name="RemoteAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("handshake", "Handshake"),
                            ("config_generated", "Config Generated"),
                            ("config_downloaded", "Config Downloaded"),
                            ("peer_added", "Peer Added to Router"),
                            ("peer_removed", "Peer Removed from Router"),
                            ("expired", "Access Expired"),
                            ("revoked", "Access Revoked"),
                            ("reactivated", "Access Reactivated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_details",
                    models.TextField(
                        blank=True, help_text="Additional event details/JSON"
                    ),
                ),
                (
                    "client_endpoint",
                    models.CharField(
                        blank=True,
                        help_text="Client IP:port as seen by the server",
                        max_length=50,
                    ),
                ),
                (
                    "bytes_sent",
                    models.BigIntegerField(default=0, help_text="Bytes sent to client"),
                ),
                (
                    "bytes_received",
                    models.BigIntegerField(
                        default=0, help_text="Bytes received from client"
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "remote_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="billing.remoteuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Denormalized for faster querying",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_access_logs",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Access Log",
                "verbose_name_plural": "Remote Access Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="remoteaccesslog",
            index=models.Index(
                fields=["tenant", "-timestamp"], name="billing_rem_tenant__ebc1d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remoteaccesslog",
            index=models.Index(
                fields=["remote_user", "-timestamp"],
                name="billing_rem_remote__3fd049_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="remoteaccesslog",
            index=models.Index(
                fields=["event_type"], name="billing_rem_event_t_67229f_idx"
            ),
        ),
    ]
