# Generated by Django 4.2 on 2026-02-23 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0022_subscriptionplan_max_remote_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteAccessPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Customer-facing plan name, e.g. 'Remote Basic Monthly'",
                        max_length=150,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Customer-facing description of the plan"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per billing cycle",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="TZS", max_length=3)),
                (
                    "promo_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Promotional/discounted price. Null = no promo.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "promo_label",
                    models.CharField(
                        blank=True,
                        help_text="Promo badge text, e.g. 'Save 20%' or 'Launch Offer'",
                        max_length=50,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly (3 months)"),
                            ("biannual", "Bi-Annual (6 months)"),
                            ("annual", "Annual (12 months)"),
                            ("custom", "Custom Days"),
                            ("unlimited", "Unlimited (No Expiry)"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "billing_days",
                    models.IntegerField(
                        default=30,
                        help_text="Duration in days this plan grants. Auto-set from billing_cycle unless custom.",
                    ),
                ),
                (
                    "bandwidth_limit_down",
                    models.IntegerField(
                        default=0,
                        help_text="Download bandwidth limit in kbps (0 = unlimited)",
                    ),
                ),
                (
                    "bandwidth_limit_up",
                    models.IntegerField(
                        default=0,
                        help_text="Upload bandwidth limit in kbps (0 = unlimited)",
                    ),
                ),
                (
                    "download_speed",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable download speed e.g. '10 Mbps'",
                        max_length=20,
                    ),
                ),
                (
                    "upload_speed",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable upload speed e.g. '5 Mbps'",
                        max_length=20,
                    ),
                ),
                (
                    "data_limit_gb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Data cap in GB per cycle. Null = unlimited.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_devices_per_user",
                    models.IntegerField(
                        default=1,
                        help_text="Number of simultaneous WireGuard peers allowed per remote user",
                    ),
                ),
                (
                    "allowed_ips",
                    models.CharField(
                        blank=True,
                        help_text="Override allowed IPs for users on this plan (empty = use VPN config default)",
                        max_length=500,
                    ),
                ),
                (
                    "full_tunnel",
                    models.BooleanField(
                        default=True,
                        help_text="True = route all traffic through VPN (0.0.0.0/0). False = split tunnel.",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Feature strings shown in portal, e.g. ["Full tunnel", "10 Mbps", "Unlimited data"]',
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower number = shown first in portal"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as popular/recommended to highlight in portal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_access_plans",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Access Plan",
                "verbose_name_plural": "Remote Access Plans",
                "ordering": ["tenant", "display_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="RemoteAccessPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="TZS", max_length=3)),
                (
                    "billing_days",
                    models.IntegerField(
                        default=30, help_text="Number of days this payment grants"
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(
                        help_text="Unique order reference for this payment",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="External payment reference (from gateway)",
                        max_length=255,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from payment gateway",
                        max_length=255,
                    ),
                ),
                (
                    "payment_channel",
                    models.CharField(
                        choices=[
                            ("clickpesa", "ClickPesa"),
                            ("snippe", "Snippe"),
                            ("manual", "Manual/Cash"),
                            ("voucher", "Voucher"),
                            ("free", "Free/Complimentary"),
                        ],
                        default="clickpesa",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number used for mobile money payment",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="The plan purchased",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.remoteaccessplan",
                    ),
                ),
                (
                    "remote_user",
                    models.ForeignKey(
                        help_text="The remote user this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.remoteuser",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_access_payments",
                        to="billing.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Access Payment",
                "verbose_name_plural": "Remote Access Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="remoteuser",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The remote access plan this user is subscribed to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remote_users",
                to="billing.remoteaccessplan",
            ),
        ),
    ]
