# Generated by Django 4.2 on 2026-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0023_remoteaccessplan_remoteaccesspayment_remoteuser_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteaccesspayment",
            name="payment_channel",
            field=models.CharField(
                choices=[
                    ("snippe", "Snippe"),
                    ("manual", "Manual/Cash"),
                    ("free", "Free/Complimentary"),
                ],
                default="snippe",
                max_length=20,
            ),
        ),
    ]
