# Generated by Django 4.2 on 2026-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0024_alter_remoteaccesspayment_payment_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteaccesspayment",
            name="payment_channel",
            field=models.CharField(
                choices=[("snippe", "Snippe")], default="snippe", max_length=20
            ),
        ),
    ]
