# Generated by Django 4.2 on 2026-02-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0025_alter_remoteaccesspayment_payment_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="ppp_support",
            field=models.BooleanField(default=False),
        ),
    ]
