# Generated by Django 4.2 on 2026-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0027_add_app_user_profile_and_phone_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="used_by_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("password_reset", "Password Reset"),
                    ("phone_verify", "Phone Verification"),
                ],
                default="password_reset",
                max_length=20,
            ),
        ),
    ]
