# Generated by Django 4.2 on 2026-02-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0028_voucher_used_by_phone_alter_phoneotp_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteaccesspayment",
            name="billing_hours",
            field=models.IntegerField(
                default=0,
                help_text="Number of hours this payment grants (for hourly plans, 0 = use billing_days)",
            ),
        ),
        migrations.AddField(
            model_name="remoteaccessplan",
            name="billing_hours",
            field=models.IntegerField(
                default=0,
                help_text="Duration in hours (for hourly plans). 0 means use billing_days instead.",
            ),
        ),
        migrations.AlterField(
            model_name="remoteaccesspayment",
            name="billing_days",
            field=models.IntegerField(
                default=30,
                help_text="Number of days this payment grants (0 if hourly plan)",
            ),
        ),
        migrations.AlterField(
            model_name="remoteaccessplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly (3 months)"),
                    ("biannual", "Bi-Annual (6 months)"),
                    ("annual", "Annual (12 months)"),
                    ("custom", "Custom Days/Hours"),
                    ("unlimited", "Unlimited (No Expiry)"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="remoteaccessplan",
            name="billing_days",
            field=models.IntegerField(
                default=30,
                help_text="Duration in days this plan grants. Auto-set from billing_cycle unless custom/hourly.",
            ),
        ),
    ]
