# Generated by Django 4.2 on 2026-02-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0029_add_billing_hours_to_vpn_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteaccesspayment",
            name="billing_minutes",
            field=models.IntegerField(
                default=0,
                help_text="Number of minutes this payment grants (for minute plans, 0 = use hours/days)",
            ),
        ),
        migrations.AddField(
            model_name="remoteaccessplan",
            name="billing_minutes",
            field=models.IntegerField(
                default=0,
                help_text="Duration in minutes (for minute-based plans, e.g. 15, 30, 45). 0 means use hours/days.",
            ),
        ),
        migrations.AddField(
            model_name="remoteuser",
            name="expiry_notification_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the 5-min-before-expiry SMS has been sent for current period",
            ),
        ),
        migrations.AlterField(
            model_name="remoteaccessplan",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("minutes", "Minutes"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly (3 months)"),
                    ("biannual", "Bi-Annual (6 months)"),
                    ("annual", "Annual (12 months)"),
                    ("custom", "Custom Duration"),
                    ("unlimited", "Unlimited (No Expiry)"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
